# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

# SERVER
server:
  port: 8080
  http2:
    enabled: true
  shutdown: graceful # timeout configuration property : spring.lifecycle.timeout-per-shutdown-phase

logging:
  level:
    root: INFO

# SPRING
spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s # format : https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-conversion-duration
  application:
    name: hero-alignlab-api
  config:
    import:
      - classpath:/config/hero-alignlab-config.yml
  output:
    ansi:
      enabled: always
  webflux:
    multipart:
      max-in-memory-size: 1024KB
      max-file-size: 5MB
      max-request-size: 10MB

# DATABASE
hero:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.hbm2ddl.auto: none
    show-sql: false
    database: mysql
    database-platform: com.hero.alignlab.config.database.CustomMySQLDialect

auth:
  jwt:
    secret:

oauth:
  kakao:
    url: https://kauth.kakao.com/oauth
    rest-api-key:
    client-secret-code:
    admin-key:
    # redirect url for get OAuth Authorize Code
    authorized-url: /authorize?client_id=%s&redirect_uri=%s&response_type=code
    redirect-url: https://api.alignlab.site/api/dev/v1/oauth/kakao/token

client:
  kakao-info:
    url: https://kapi.kakao.com
    unlink-path: /v1/user/unlink
  discord:
    webhook:
      url:

encrypt:
  key:
  algorithm:

hero-alignlab:
  dev:
    resource:
      key:

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: alignlab-public-s3
      bucketUrl: https://alignlab-public-s3.s3.ap-northeast-2.amazonaws.com
      cdnUrl: https://cdn.alignlab.site
    region:
      static: ap-northeast-2
    stack:
      auto: false
