# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

# SERVER
server:
  port: 8080
  http2:
    enabled: true
  shutdown: graceful # timeout configuration property : spring.lifecycle.timeout-per-shutdown-phase

logging:
  level:
    root: INFO

# SPRING
spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s # format : https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-conversion-duration
  application:
    name: hero-alignlab-api
  config:
    import:
      - classpath:/config/hero-alignlab-config.yml

# DATABASE
hero:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibrenate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.hbm2ddl.auto: none
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

auth:
  jwt:
    secret:

oauth:
  kakao:
    url: https://kauth.kakao.com/oauth
    rest-api-key:
    client-secret-code:
    # redirect url for get OAuth Authorize Code
    authorized-url: /authorize?client_id=%s&redirect_uri=%s&response_type=code
    redirect-url: https://api.alignlab.site/api/dev/v1/oauth/kakao/token

encrypt:
  key:
  algorithm:

hero-alignlab:
  dev:
    resource:
      key:
